### ISSUE TITLE
Failed create app on Nuxt.js

### ISSUE THREAD

**Issue by nojimage** [line/create-liff-app#27]
# 🐛 Bug Report 

I can't create an app with the Nuxt.js template using the 'create-liff-app' command.

## 💁 Possible Solution

In Stack trace, I've got `at GeneratorContext.actions (~/node_modules/create-nuxt-app/lib/saofile.js:81:22)`

The code looks like this:

https://github.com/nuxt/create-nuxt-app/blob/2f58b48a9e1fb3f78c465569e8441313cfc89642/packages/create-nuxt-app/lib/saofile.js#L81

```js
    if (this.answers.template !== 'html') {
      actions.push({
        type: 'add',
        files: '**',
        templateDir: join(frameworksDir, this.answers.template)
      })
    }
```

I speculate that the error is happening because there is no 'template' specification in the 'answers' option sent to 'create-nuxt-app'.

## 💻 Code Sample

Reproduction steps ＆ Error logs:

```sh
npx @line/create-liff-app -t nuxtjs --ts --npm liff-app
Welcome to the Create LIFF App
? Please enter your LIFF ID: 
 Don't you have LIFF ID? Check out https://developers.line.biz/ja/docs/liff/getting-started/ liffId

Generating liff app using `create-app`, this might take a while.


create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in liff-app
Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at GeneratorContext.actions (/root/.npm/_npx/ea7c6e7510ea3309/node_modules/create-nuxt-app/lib/saofile.js:81:22)
    at module.exports (/root/.npm/_npx/ea7c6e7510ea3309/node_modules/sao/lib/runActions.js:12:30)
    at SAO.runGenerator (/root/.npm/_npx/ea7c6e7510ea3309/node_modules/sao/lib/index.js:133:36)
    at SAO.run (/root/.npm/_npx/ea7c6e7510ea3309/node_modules/sao/lib/index.js:101:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
    at /root/.npm/_npx/ea7c6e7510ea3309/node_modules/create-nuxt-app/lib/cli.js:56:19
{
  command: 'npx create-nuxt-app liff-app --answers {"name":"liff-app","pm":"npm","language":"ts","features":["axios"],"linter":["eslint"],"ui":"none","test":"none","mode":"universal","target":"server","devTools":"none","vcs":"none"}'
}
```

## 🌍 Your Environment

- Node.js v18.15.0
- npm 9.6.6

**Comment by nojimage** [comment]
Could it be that create-liff-app doesn't yet support create-nuxt-app 5.0?
